Import-Module WebAdministration; 

 
$pool='TC-CODIGO-POSTAL-API','TC-CONCEPTOSSOCIOS-API','TC-CUENTAS-API','TC-DOMICILIOS-API','TC-ENTIDADES-API','TC-ESTABLECIMIENTOS-API','TC-ESTADOS-API','TC-ESTADOSTIPO-API','TC-FORMASPAGO-API',
'TC-GRUPOAFINIDAD-API','TC-MONEDAS-API','TC-PARAMETERS-API','TC-PERSONAS-API','TC-PRODUCTOS-API','TC-SOCIOS-API','TC-TIPOSCUENTAS-API','TC-TIPOSDOCUMENTOS-API','TC-ESTADOSACTIVIDADES-API',
'TC-ESTADOSCIVILES-API','TC-FERIADOS-API','TC-MARCAS-API','TC-MODELOSBONIFICACIONES-API','TC-MODELOSLIMITES-API','TC-PAISES-API','TC-PROVINCIAS-API','TC-SUCURSALESENTIDAD-API','TC-TIPOSPRODUCTO-API',
'TC-CUENTACREDITOS-API','TC-MODELOSAUT-API','TC-MOTIVOSNORENOVACION-API','TC-COMPANIASSEGUROS-API','TC-ENTIDADESSERVICES-API','TC-GRUPOSCIERRE-API','TC-MODELOLIQUIDACION-API',
'TC-POSICIONIMPOSITIVA-API','TC-RT11001-API','TC-SOCIOSGATEWAY-API','TC-SUBMODELOPARAMETROS-API','TC-SUBMODELOSCARGOS-API','TC-SUBMODELOTASAS-API','TC-GENEROS-API','TC-TARJETAS-API','TC-SOCIOSERRORES-API'

foreach($pooln in $pool){

$po=Get-ChildItem -Path IIS:\AppPools |Select-Object -Property name|Select-String -CaseSensitive $pooln

if($po -ne $null ){
Remove-WebAppPool -Name $pooln -ErrorAction Continue
Write-Host 'el pool'$pooln 'fue borrado'
}
Write-Host 'el Pool'$pooln 'No existe'

}
