# syntax=docker/dockerfile:1

FROM alpine:3.10

#copy . /Web-app 
RUN apk add python3-dev \
   && apk add curl \
   && pip3 install --upgrade pip \
   && pip install requests \
   && pip install flask
WORKDIR /Web-app
LABEL "clustername"="elastic"
ENTRYPOINT [ "python3" ]
CMD  ["index.py"]